name: Build & Deploy to Github Pages

on:
  push:
    branches: [master, main]

permissions:
  contents: write

jobs:
  node-to-gh:
    name: Build & Deploy to Github Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./beerxp
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
        shell: bash
      - run: npm run build
        shell: bash
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: beerxp/build
